import type { Metadata } from "next";
import { Inter, Raleway } from 'next/font/google'
import "./globals.css";


// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter',
})

const raleway = Raleway({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-raleway',
})

export const metadata: Metadata = {
  title: "Vikram Krishnakumar",
  // description: "Generated by create next app",
};

export default function RootLayout({
        children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className={`${inter.variable} ${raleway.variable} antialiased`}>
        <body>{children}</body>
        </html>
    )
}
